stages:
  - build
  - deploy

variables:
  DATABASE_URL: sqlite:///app/db.sqlite3

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t shoppinglyx .

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploy step - customize this according to your deployment process"
    - docker-compose up -d
  only:
    - main