# Generated by Django 5.0.3 on 2024-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('An Giang', 'An Giang'), ('Bà Rịa - Vũng Tàu', 'Ba Ria - Vung Tau'), ('Bắc Giang', 'Bac Giang'), ('Bắc Kạn', 'Bac Kan'), ('Bạc Liêu', 'Bac Lieu'), ('Bắc Ninh', 'Bac Ninh'), ('Bến Tre', 'Ben Tre'), ('Bình Định', 'Binh Dinh'), ('Bình Dương', 'Binh Duong'), ('Bình Phước', 'Binh Phuoc'), ('Bình Thuận', 'Binh Thuan'), ('Cà Mau', 'Ca Mau'), ('Cao Bằng', 'Cao Bang'), ('Đắk Lắk', 'Dak Lak'), ('Đắk Nông', 'Dak Nong'), ('Điện Biên', 'Dien Bien'), ('Đồng Nai', 'Dong Nai'), ('Đồng Tháp', 'Dong Thap'), ('Gia Lai', 'Gia Lai'), ('Hà Giang', 'Ha Giang'), ('Hà Nam', 'Ha Nam'), ('Hà Tĩnh', 'Ha Tinh'), ('Hải Dương', 'Hai Duong'), ('Hậu Giang', 'Hau Giang'), ('Hòa Bình', 'Hoa Binh'), ('Hưng Yên', 'Hung Yen'), ('Khánh Hòa', 'Khanh Hoa'), ('Kiên Giang', 'Kien Giang'), ('Kon Tum', 'Kon Tum'), ('Lai Châu', 'Lai Chau'), ('Lâm Đồng', 'Lam Dong'), ('Lạng Sơn', 'Lang Son'), ('Lào Cai', 'Lao Cai'), ('Long An', 'Long An'), ('Nam Định', 'Nam Dinh'), ('Nghệ An', 'Nghe An'), ('Ninh Bình', 'Ninh Binh'), ('Ninh Thuận', 'Ninh Thuan'), ('Phú Thọ', 'Phu Tho'), ('Quảng Bình', 'Quang Binh'), ('Quảng Nam', 'Quang Nam'), ('Quảng Ngãi', 'Quang Ngai'), ('Quảng Ninh', 'Quang Ninh'), ('Quảng Trị', 'Quang Tri'), ('Sóc Trăng', 'Soc Trang'), ('Sơn La', 'Son La'), ('Tây Ninh', 'Tay Ninh'), ('Thái Bình', 'Thai Binh'), ('Thái Nguyên', 'Thai Nguyen'), ('Thanh Hóa', 'Thanh Hoa'), ('Thừa Thiên Huế', 'Thua Thien Hue'), ('Tiền Giang', 'Tien Giang'), ('Trà Vinh', 'Tra Vinh'), ('Tuyên Quang', 'Tuyen Quang'), ('Vĩnh Long', 'Vinh Long'), ('Vĩnh Phúc', 'Vinh Phuc'), ('Yên Bái', 'Yen Bai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop')], max_length=2),
        ),
    ]
